### ISSUE TITLE
【求助】cardList分类切换问题

### ISSUE THREAD

**Issue by sandmanman** [super-summer/fis-vue-weibo#1]
你好：用了你的DEMO做学习。为什么在切换分类的时候，cardList显示的并不是对应的分类下的列表。
谢谢！
getCardList:function(cate){
            console.log("取得" + cate +"列表");
            //此处应该根据cate 去请求接口
            var self = this;
            $.ajax({
                url:"build/src/data.json",
                type:"GET",
                dataType:"JSON",
                success:function(cards){
                    console.log("返回了card 列表：",cards);
                    self.$data.cardList = cards;
                },
                error:function(){
                    console.log("调数据错了");
                }
            });
    },

**Comment by super-summer** [comment]
这里请求数据时是要用到参数 cate的， 响应数据的时候应该根据cate来返回不同的数据， 我没有处理所以显示出来是一样的列表，但是cate 值是发生了变化的。
